[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default.csv
; ESP32 Arduino 自带 BLE (BLEDevice.h), 无需额外 lib_deps
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
